const BACKEND_BASE_URL = "http://localhost:8080";
const API_BASE_URL = `${BACKEND_BASE_URL}/api`;

const SNIPPETS_BASE_URL = `${API_BASE_URL}/snippets`;
const SNIPPETS_RAW_BASE_URL = `${SNIPPETS_BASE_URL}/raw`;
const SNIPPETS_DATA_BASE_URL = `${SNIPPETS_BASE_URL}/data`;
const SNIPPETS_UPLOAD_URL = `${SNIPPETS_BASE_URL}/upload`;

export {
  BACKEND_BASE_URL,
  API_BASE_URL,
  SNIPPETS_BASE_URL,
  SNIPPETS_RAW_BASE_URL,
  SNIPPETS_DATA_BASE_URL,
  SNIPPETS_UPLOAD_URL
};
